### PR TITLE
Main listing Chapter

### LINKED ISSUE #3: List View
Using the pokedex view (list of pokemon) as an example. https://github.com/rangle/react-native-workshop/blob/master/src/containers/Pokedex.js

### PR DESCRIPTION
**Pull request by sachasayan**
Tried to strike a balance on this, let me know what you guys think.

closes #3

### CODE REVIEW

**Comment by riavalon** [comment]
Looks good to me! :shipit:

**Comment by winkerVSbecks** [comment]
@ssayan you can probably leave the search filter out since that's going to be in the section @riavalon is working on. We can probably reuse your content. Also for the code examples could you add ` ```js` to enable syntax highlighting. Thanks

**Comment by riavalon** [comment]
@winkerVSbecks I only really touch on the implementation of the selector, and just sort of build that on top of using the search component mentioned in this chapter.

**Comment by winkerVSbecks** [comment]
@riavalon ok didn't realize that. @ssayan don't worry about modifying that part then. Just the syntax highlighting and then :shipit:

**Pull request merged**
